Repository sonatype-nexus-community/auditjs, pull requests merged in 2020-02, with the labels that each got.

#148 Bower Dev Dependencies
  src/Application/Application.ts
  src/Munchers/Bower.ts
Labels: enhancement, release 4.0.0

#151 Design tweakin
  package-lock.json
  src/Application/Application.ts
  src/Audit/AuditIQServer.ts
  src/Audit/AuditOSSIndex.ts
  src/Visual/VisualHelper.ts
Labels: enhancement, release 4.0.0

#152 Fix bug where if @types/lib and lib exist and have same version, only one showed up
  package.json
  src/Munchers/NpmList.ts
Labels: bug

#154 fix: Logs are cleared with each run of AuditJS
  src/Application/Logger/Logger.ts
Labels: enhancement, release 4.0.0

#158 fix: Added section to README to mention Version 77+ of Nexus IQ needed for AuditJS
  README.md
Labels: enhancement, release 4.0.0

#159 Show usage for any command we don't actually support
  src/index.ts
Labels: bug, release 4.0.0

#160 CycloneDX Inhouse Implementation
  package-lock.json
  package.json
  src/CycloneDX/CycloneDXSbomCreator.spec.ts
  src/CycloneDX/CycloneDXSbomCreator.ts
  src/CycloneDX/Options.ts
  src/CycloneDX/Types/Component.ts
  src/CycloneDX/Types/ExternalReference.ts
  src/CycloneDX/Types/Hash.ts
  src/CycloneDX/Types/LicenseContent.ts
  src/CycloneDX/typings/packageurl-js/index.d.ts
  src/CycloneDX/typings/parse-packagejson-name/index.d.ts
  src/CycloneDX/typings/read-installed/index.d.ts
  src/Munchers/NpmList.ts
  src/Services/IqRequestService.ts
  tsconfig.json
  types/cyclonedx__bom/index.d.ts
Labels: enhancement, release 4.0.0

#156 bug: yarn project was not bringing back any dependencies
  src/Munchers/NpmList.ts
Labels: bug, release 4.0.0

#161 fix: Sorting vulnerabilities (high to low) and change colors
  src/Audit/AuditOSSIndex.ts
Labels: enhancement, release 4.0.0

#171 Suggest to run with dev flag if 0 dependencies are found
  src/Audit/AuditOSSIndex.ts
Labels: enhancement, release 4.0.0

#166 Moving from Winston to Log4JS
  README.md
  package-lock.json
  package.json
  src/Application/Application.ts
  src/Application/Logger/Logger.ts
  src/Config/Config.ts
  src/Config/IqServerConfig.ts
  src/Config/OssIndexServerConfig.ts
  src/Services/IqRequestService.spec.ts
  src/Services/IqRequestService.ts
  src/index.ts
Labels: bug, release 4.0.0
